name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install valgrind
      run: sudo apt install valgrind

    - name: make all valgrind test
      run: make av

    - name: make fclean
      run: make fclean
